name: Create and Copy Zip to Releases Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Retrieve version from system.json
      id: get_version
      run: echo "VERSION=$(jq -r .version system.json)" >> $GITHUB_ENV

    - name: Create zip file
      run: zip -r v${{ env.VERSION }}.zip .

    - name: Checkout releases branch
      run: git checkout -b releases origin/releases || git checkout releases

    - name: Copy zip file to releases branch
      run: |
        git add v${{ env.VERSION }}.zip
        git commit -m "Add new release zip v${{ env.VERSION }}"
        git push origin releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}