name: Create and Copy Zip to Another Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "lionel.courgnaud@gmail.com"
        git config --global user.name "LionelCourgnaud"

    - name: Retrieve version from system.json
      id: get_version
      run: echo "VERSION=$(jq -r .version system.json)" >> $GITHUB_ENV

    - name: Create zip file
      run: zip -r v${{ env.VERSION }}.zip .

    - name: Checkout RnP_Releases repository
      run: |
        git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/LionelCourgnaud/RnP_Releases.git
        cd RnP_Releases
        git checkout main

    - name: Copy and commit zip file to RnP_Releases repository
      run: |
        cp v${{ env.VERSION }}.zip RnP_Releases/
        cd RnP_Releases
        git add v${{ env.VERSION }}.zip
        git commit -m "Add new release zip v${{ env.VERSION }}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}