name: Create and Copy zip to the releases Branch

on:
  push:
    branches:
      - releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases branch
        uses: actions/checkout@v2
        with:
          ref: releases
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "lionel.courgnaud@gmail.com"
          git config --global user.name "LionelCourgnaud"

      - name: Merge main branch into releases
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin main
          git merge origin/main --allow-unrelated-histories

      - name: Retrieve version from system.json
        id: get_version
        run: echo "VERSION=$(jq -r .version system.json)" >> $GITHUB_ENV

      - name: Create clean zip file
        run: |
          # Créer une liste de fichiers à inclure, en excluant explicitement .git et .github
          find . -type f \
          ! -path "./.git/*" \
          ! -path "./archives/*" \
          ! -path "./archives" \
          ! -path "./.github/*" \
          ! -path "./v*.zip" \
          ! -name ".git*" \
          ! -name ".DS_Store" \
          > files_to_zip.txt
          
          # Afficher la liste pour vérification
          echo "Files to be included in zip:"
          cat files_to_zip.txt
          
          # Créer le zip en utilisant uniquement les fichiers listés
          zip v${{ env.VERSION }}.zip -@ < files_to_zip.txt
          
          # Vérifier le contenu du zip
          echo "Zip contents:"
          unzip -l v${{ env.VERSION }}.zip
          mv -f v${{ env.VERSION }}.zip ./archives/
          git status

      - name: Add and commit zip file to releases branch
        run: |
          git add archives/v${{ env.VERSION }}.zip
          git commit -m "Add new release zip v${{ env.VERSION }}"
          git push origin releases
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}